# Generated by Django 3.2.6 on 2021-08-13 09:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1', models.CharField(max_length=6)),
                ('adm0_en', models.CharField(max_length=50)),
                ('population', models.CharField(max_length=254)),
                ('male_pop', models.CharField(max_length=254)),
                ('female_pop', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
