# Generated by Django 3.2.6 on 2021-08-13 11:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20210813_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1', models.CharField(max_length=6)),
                ('pcode', models.CharField(max_length=9)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Warehouse',
                'db_table': 'geo_warehouse',
            },
        ),
    ]
